### PR TITLE
Add Dark Mode to Slides

### PR DESCRIPTION
**Pull request by sarthaktexas**

### CODE REVIEW

**Comment by sarthaktexas** [comment]
WAIT WAIT DO NOT MERGE THIS IT'S NOT DONE YET

**Comment by sarthaktexas** [comment]
wait a minute, looks like y'all purposely disabled dark mode detection... any specific reason?

**Comment by sarthaktexas** [comment]
It's like 3:11 am over here and I'm looking at the brightttt slides and it's hurting my eyes.

**Comment by sarthaktexas** [comment]
Ok, everything I want (or at least that I can see) should be dark moded. If y'all want, merge it :)

**Comment by lachlanjc** [comment]
We actually decided not to have dark mode on the site since we didn’t want to implement a theme switcher, & otherwise once you’re in dark/light mode, there’s no way to change it without clearing your localstorage. Thank you for the PR though!

**Pull request closed without merging**
